### ISSUE TITLE
Supports Node 16.X?

### ISSUE THREAD

**Issue by sefirosweb** [TheDudeFromCI/mineflayer-statemachine#113]
Hello i'm trying to install this package in updated node version and i have error when install this dependency

![image](https://user-images.githubusercontent.com/20754836/131210931-9dacede3-49d1-41c1-83e8-37862e21220e.png)

You know if this dependency supports node 16?
From node 14 seems works fine

package.json:
![image](https://user-images.githubusercontent.com/20754836/131210954-fe64bcb9-6278-4fbd-a83e-29cd5984a7f2.png)

**Comment by nickelpro** [comment]
Read the error message, you have a cache permission issue

**Comment by sefirosweb** [comment]
Nevermind seems a issue about executed by root instead a normal user
